#!/bin/bash
set -eu

# Get from version control FPC, Lazarus and build + install them system-wide.

# see https://svn.freepascal.org/cgi-bin/viewvc.cgi/tags/release_3_2_0_rc1/
# https://www.freepascal.org/develop.html

FPC_BRANCHTAG='tags/release_3_2_2/'
LAZARUS_BRANCHTAG='tags/lazarus_2_0_12/'
FPC_DIR_NAME='3.2.2'
LAZARUS_DIR_NAME='2.0.12'

do_get_fpc_lazarus ()
{
  rm -Rf ~/sources/fpc/ ~/sources/lazarus/
  mkdir ~/sources/fpc/ ~/sources/lazarus/

  cd ~/sources/fpc/
  svn co https://svn.freepascal.org/svn/fpc/"${FPC_BRANCHTAG}" "${FPC_DIR_NAME}"

  cd ~/sources/lazarus/
  svn co https://svn.freepascal.org/svn/lazarus/"${LAZARUS_BRANCHTAG}" "${LAZARUS_DIR_NAME}"
}

do_install_fpc ()
{
  cd ~/sources/fpc/"${FPC_DIR_NAME}"/

  # ONCE: get fpc from packages to bootstrap
  # sudo apt install fpc

  export FPC_INSTALL_DIR="${HOME}"/installed/fpc
  mkdir -p "${FPC_INSTALL_DIR}"
  make clean all install INSTALL_PREFIX="${FPC_INSTALL_DIR}"
  cd ~/installed/fpc/bin && ln -s ../lib/fpc/"${FPC_DIR_NAME}"/ppcarm .

  # ONCE: fix after "apt install fpc"
  # purge FPC from packages, but leave some useful dev libraries like GTK
  # sudo apt purge fpc
  # sudo apt install libgtk2.0-dev libglu1-mesa-dev
  # sudo apt --purge autoremove

  # ONCE: make the new FPC on $PATH, in ~/.profile

  # make system-wide ------------------------------------------

  sudo rm -Rf /usr/local/fpc
  sudo mv "${HOME}"/installed/fpc /usr/local
  sudo chown -R root:root /usr/local/fpc
  
  # make symlinks, used e.g. by /etc/fpc.cfg, and FPCDIR in /home/jenkins/.bashrc
  rm -f /usr/local/fpc/lib/fpc/current/
  ln -s "${FPC_DIR_NAME}" /usr/local/fpc/lib/fpc/current

  # test ----------------------------------------

  cd ~/sources/
  # test new fpc
  echo 'begin writeln(2+2) end.' > a.pas
  fpc -l
  fpc a.pas
  ./a
}

do_install_lazarus ()
{
  cd ~/sources/lazarus/"${LAZARUS_DIR_NAME}"/
  export LAZ_INSTALL_DIR="${HOME}"/installed/lazarus
  mkdir -p "${LAZ_INSTALL_DIR}"
  make clean all install INSTALL_PREFIX="${LAZ_INSTALL_DIR}"

  # ONCE: make lazarus lazbuild on $PATH in ~/.profle

  # make system-wide -------------------------------------------------

  sudo rm -Rf /usr/local/lazarus
  sudo mv "${HOME}"/installed/lazarus /usr/local
  sudo mv "${HOME}"/sources/lazarus/"${LAZARUS_DIR_NAME}" /usr/local/lazarus/src

  # fix lazbuild to work, by passing --lazarusdir
  sudo mv /usr/local/lazarus/bin/lazbuild  /usr/local/lazarus/bin/lazbuild-real
  sudo bash -c 'cat > /usr/local/lazarus/bin/lazbuild <<EOF
#!/bin/bash
set -eu

# DO NOT EDIT - this file is auto-generated and may be overridden.
# Created by CGE FPC/Lazarus compilation script for Raspberry Pi.

/usr/local/lazarus/bin/lazbuild-real --lazarusdir=/usr/local/lazarus/src "\$@"
EOF'
  sudo chmod +x /usr/local/lazarus/bin/lazbuild

  sudo chown -R root:root /usr/local/lazarus

  # test ---------------------------------------------------

  lazbuild --version
}

do_cge ()
{
  cd ~/sources/castle-engine/
  git clone https://github.com/castle-engine/castle-engine/

  cd ~/sources/castle-engine/castle-engine/
  # make tools
  mkdir -p "${HOME}"/installed/castle-engine
  make install PREFIX="${HOME}"/installed/castle-engine
  export CASTLE_ENGINE_PATH="${HOME}/sources/castle-engine/castle-engine/"
  export PATH="${PATH}:${HOME}/installed/castle-engine/bin"
  make examples
  make examples-laz
  make tests
  make test-fpmake
  ./tools/internal/pack_release/pack_release.sh linux arm
}

# As we're extra short on disk space, remove unnecessary leftovers from ~/sources and ~/installed
do_clean ()
{
  rm -Rf \
    "${HOME}"/sources/fpc/"${FPC_DIR_NAME}" \
    "${HOME}"/sources/lazarus/"${LAZARUS_DIR_NAME}" \
    "${HOME}"/installed/fpc \
    "${HOME}"/installed/lazarus
}

do_get_fpc_lazarus
do_install_fpc
do_install_lazarus
#do_cge # just a test - no longer useful, Jenkins does CGE on this host now
do_clean
