#!/bin/sh
set -eu

valgrind --tool=massif --run-libc-freeres=no \
  --alloc-fn='CMEM_CGETMEM$LONGWORD$$POINTER' \
  --alloc-fn='CMEM_CGETMEM$LONGINT$$POINTER' \
  --alloc-fn='CMEM_CREALLOCMEM$POINTER$LONGWORD$$POINTER' \
  --alloc-fn='CMEM_CREALLOCMEM$POINTER$LONGINT$$POINTER' \
  --alloc-fn='SYSTEM_GETMEM$LONGWORD$$POINTER' \
  --alloc-fn='SYSTEM_GETMEM$LONGINT$$POINTER' \
  --alloc-fn='SYSTEM_GETMEM$POINTER$LONGWORD' \
  --alloc-fn='SYSTEM_GETMEM$POINTER$LONGINT' \
  --alloc-fn='SYSTEM_REALLOCMEM$POINTER$LONGWORD$$POINTER' \
  --alloc-fn='SYSTEM_REALLOCMEM$POINTER$LONGINT$$POINTER' \
  "$@"

# --format=html was useful with previous massif versions, but it seems not available anymore?
