#!/bin/bash
set -eu

# Convert 6 images rendered_background000x.bmp (typically done by
# Terragen script generated by gen_make_skycube.sh)
# to 6 images named $1_back/bottom/front/left/right/top.png.
# Such 6 image names are better suited for VRML Background url names,
# and PNG format is of course much better than bmp.

TARGET_PREFIX="$1"
shift 1

doit ()
{
  INPUT=rendered_background000"$1".bmp
  OUTPUT="$TARGET_PREFIX"_"$2".png
  convert "$INPUT" "$OUTPUT"
  echo 'Made '"$OUTPUT"
  rm -f "$INPUT"
}

doit 1 left
doit 2 back
doit 3 right
doit 4 front
doit 5 bottom
doit 6 top
